[package]
name = "feather-cli"
version = "0.1.1"
edition = "2024"
authors = ["Bersis Sevimli"]
description = "A CLI for Feather"
license = "MIT"
readme = "README.md"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
notify = "8.0.0"
